name: First Workflow

on:
  workflow_dispatch

env:
  MIKE_VAR: 12345
  
jobs:
  firstjob:
    name: First Job
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Flash Gordon'

      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"
          
      - name: Dispay my var
        shell: pwsh
        run: echo ${env.MIKE_VAR}
        
  secondjob:
    name: Second Job
    needs: [firstjob]
    runs-on: ubuntu-latest
    steps:
      - name: Second Job - Ubuntu
        shell: bash
        run: |
          echo This is the second job
          echo Multi-line script
    
